import Head from "next/head";
import { useRouter } from "next/router";
import Navbar from "../../components/Navbar";
import ProjectContainer from "../../containers/Project";

export default function Project() {
  const router = useRouter();

  const route = router.query.projectName;
  console.log("router", route);

  return (
    <>
      <Head>
        <title>Maker Bros - Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <ProjectContainer />
    </>
  );
}
