import Head from "next/head";
import Navbar from "../../components/Navbar";
import LandingPage from "../../containers/LandingPage";

export default function Work() {
  return (
    <>
      <Head>
        <title>Maker Bros - Work</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <LandingPage />
    </>
  );
}
